# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
   secret_key_base: b93d0329d49f23c2ea241a2e4142a465b0c2c6ef155768c7268a0d928d6f8aa0c1afe49a933943727fdb28bb26b1703fae6462b1e7aebe5b3aca5fbbcfc22f25
   nyt_api_key: <%= ENV["NYT_API_KEY"] %>

test:
   secret_key_base: c8386ca9879b8dbbba76317bfce55977eea096ec41c2386624283cc62970e1cdeafd7e63206dea4c98b365739d9f679a75b94a33861572ada5597f0e4d161810
   nyt_api_key: <%= ENV["NYT_API_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
   nyt_api_key: <%= ENV["NYT_API_KEY"] %>
